import type { User, Course, Enrollment, Review, ChatMessage, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Sami Trabelsi',
    email: 'admin@eduai.tn',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin1',
    bio: 'Administrateur plateforme EduAI Pro',
    joinedAt: '2024-01-01',
    isActive: true,
  },
  {
    id: 'trainer-1',
    name: 'Dr. Amira Ben Salah',
    email: 'amira@eduai.tn',
    role: 'trainer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer1',
    bio: 'Experte en Intelligence Artificielle et Machine Learning avec 10 ans d\'expérience.',
    joinedAt: '2024-01-15',
    isActive: true,
  },
  {
    id: 'trainer-2',
    name: 'Mohamed Khelifi',
    email: 'mohamed@eduai.tn',
    role: 'trainer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer2',
    bio: 'Développeur Full-Stack senior, spécialisé React et Node.js',
    joinedAt: '2024-02-01',
    isActive: true,
  },
  {
    id: 'student-1',
    name: 'Youssef Mansouri',
    email: 'youssef@student.tn',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student1',
    joinedAt: '2024-03-01',
    isActive: true,
  },
  {
    id: 'student-2',
    name: 'Fatma Gharbi',
    email: 'fatma@student.tn',
    role: 'student',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student2',
    joinedAt: '2024-03-10',
    isActive: true,
  },
];

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Intelligence Artificielle & Machine Learning avec Python',
    description: 'Maîtrisez les fondamentaux de l\'IA et du ML. De la régression linéaire aux réseaux de neurones profonds, avec des projets pratiques sur des données réelles.',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    category: 'Intelligence Artificielle',
    level: 'Intermédiaire',
    duration: 42,
    lessonsCount: 68,
    studentsCount: 1248,
    rating: 4.9,
    ratingsCount: 387,
    trainerId: 'trainer-1',
    trainerName: 'Dr. Amira Ben Salah',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer1',
    tags: ['Python', 'ML', 'Deep Learning', 'TensorFlow', 'Scikit-learn'],
    isPublished: true,
    createdAt: '2024-01-20',
    updatedAt: '2024-11-15',
    price: 0,
    language: 'Français',
  },
  {
    id: 'course-2',
    title: 'Développement Full-Stack avec React & Spring Boot',
    description: 'Construisez des applications web modernes de A à Z. Frontend avec React/TypeScript, Backend avec Spring Boot, Base de données avec PostgreSQL.',
    thumbnail: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&q=80',
    category: 'Développement Web',
    level: 'Avancé',
    duration: 56,
    lessonsCount: 92,
    studentsCount: 876,
    rating: 4.8,
    ratingsCount: 256,
    trainerId: 'trainer-2',
    trainerName: 'Mohamed Khelifi',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer2',
    tags: ['React', 'Spring Boot', 'TypeScript', 'PostgreSQL', 'Docker'],
    isPublished: true,
    createdAt: '2024-02-10',
    updatedAt: '2024-11-20',
    price: 299,
    language: 'Français',
  },
  {
    id: 'course-3',
    title: 'DevOps & Cloud : Docker, Kubernetes & CI/CD',
    description: 'Automatisez vos déploiements et gérez des infrastructures cloud à grande échelle. Maîtrisez les outils DevOps modernes utilisés en entreprise.',
    thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&q=80',
    category: 'DevOps',
    level: 'Avancé',
    duration: 38,
    lessonsCount: 54,
    studentsCount: 654,
    rating: 4.7,
    ratingsCount: 189,
    trainerId: 'trainer-1',
    trainerName: 'Dr. Amira Ben Salah',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer1',
    tags: ['Docker', 'Kubernetes', 'Jenkins', 'AWS', 'CI/CD'],
    isPublished: true,
    createdAt: '2024-03-05',
    updatedAt: '2024-11-10',
    price: 249,
    language: 'Français',
  },
  {
    id: 'course-4',
    title: 'Data Science avec Python & Pandas',
    description: 'Analysez et visualisez des données complexes. Maîtrisez Pandas, NumPy, Matplotlib et créez des tableaux de bord analytiques interactifs.',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    category: 'Data Science',
    level: 'Intermédiaire',
    duration: 30,
    lessonsCount: 48,
    studentsCount: 923,
    rating: 4.8,
    ratingsCount: 312,
    trainerId: 'trainer-1',
    trainerName: 'Dr. Amira Ben Salah',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer1',
    tags: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn'],
    isPublished: true,
    createdAt: '2024-02-20',
    updatedAt: '2024-10-30',
    price: 199,
    language: 'Français',
  },
  {
    id: 'course-5',
    title: 'Cybersécurité : Ethical Hacking & Pentest',
    description: 'Apprenez à sécuriser les systèmes en pensant comme un hacker éthique. Tests de pénétration, analyse de vulnérabilités, et protection des infrastructures.',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    category: 'Cybersécurité',
    level: 'Avancé',
    duration: 45,
    lessonsCount: 72,
    studentsCount: 543,
    rating: 4.9,
    ratingsCount: 167,
    trainerId: 'trainer-2',
    trainerName: 'Mohamed Khelifi',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer2',
    tags: ['Kali Linux', 'OWASP', 'Metasploit', 'Burp Suite', 'CTF'],
    isPublished: true,
    createdAt: '2024-04-01',
    updatedAt: '2024-11-01',
    price: 349,
    language: 'Français',
  },
  {
    id: 'course-6',
    title: 'Développement Mobile Flutter & Dart',
    description: 'Créez des applications mobiles cross-platform avec Flutter. De l\'interface utilisateur aux API REST, en passant par Firebase et les notifications push.',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80',
    category: 'Mobile',
    level: 'Débutant',
    duration: 32,
    lessonsCount: 52,
    studentsCount: 789,
    rating: 4.7,
    ratingsCount: 234,
    trainerId: 'trainer-2',
    trainerName: 'Mohamed Khelifi',
    trainerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trainer2',
    tags: ['Flutter', 'Dart', 'Firebase', 'iOS', 'Android'],
    isPublished: true,
    createdAt: '2024-05-10',
    updatedAt: '2024-11-05',
    price: 229,
    language: 'Français',
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'enr-1',
    userId: 'student-1',
    courseId: 'course-1',
    enrolledAt: '2024-09-01',
    progress: 72,
    lastAccessedAt: '2024-11-22',
    completedLessons: [],
    isCompleted: false,
  },
  {
    id: 'enr-2',
    userId: 'student-1',
    courseId: 'course-2',
    enrolledAt: '2024-10-15',
    progress: 35,
    lastAccessedAt: '2024-11-21',
    completedLessons: [],
    isCompleted: false,
  },
  {
    id: 'enr-3',
    userId: 'student-1',
    courseId: 'course-4',
    enrolledAt: '2024-08-20',
    progress: 100,
    lastAccessedAt: '2024-11-10',
    completedLessons: [],
    isCompleted: true,
    completedAt: '2024-11-10',
    certificateUrl: '#',
  },
  {
    id: 'enr-4',
    userId: 'student-2',
    courseId: 'course-1',
    enrolledAt: '2024-09-15',
    progress: 45,
    lastAccessedAt: '2024-11-20',
    completedLessons: [],
    isCompleted: false,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    userId: 'student-1',
    courseId: 'course-1',
    rating: 5,
    comment: 'Formation exceptionnelle ! Dr. Amira explique les concepts complexes de manière très claire et accessible. Les projets pratiques sont vraiment enrichissants.',
    userName: 'Youssef Mansouri',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student1',
    createdAt: '2024-11-10',
    isVerified: true,
  },
  {
    id: 'review-2',
    userId: 'student-2',
    courseId: 'course-1',
    rating: 5,
    comment: 'Le meilleur cours d\'IA en langue française ! La progression pédagogique est parfaite et le support du formateur est très réactif.',
    userName: 'Fatma Gharbi',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=student2',
    createdAt: '2024-11-05',
    isVerified: true,
  },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'msg-0',
    role: 'assistant',
    content: 'Bonjour ! Je suis **EduBot**, votre assistant IA pédagogique. Je peux vous aider à comprendre les concepts de vos cours, répondre à vos questions, et vous guider dans votre parcours d\'apprentissage. Comment puis-je vous aider aujourd\'hui ?',
    timestamp: new Date().toISOString(),
  },
];

export const aiResponses: Record<string, string> = {
  default: 'C\'est une excellente question ! Basé sur votre progression actuelle dans le cours, je vous recommande de revoir les concepts fondamentaux avant d\'avancer. Avez-vous des questions spécifiques sur ce sujet ?',
  ml: 'Le Machine Learning est un sous-domaine de l\'Intelligence Artificielle qui permet aux systèmes d\'apprendre automatiquement à partir des données. Les principales catégories sont :\n\n**1. Apprentissage supervisé** : Le modèle apprend à partir de données étiquetées\n**2. Apprentissage non supervisé** : Le modèle découvre des patterns dans des données non étiquetées\n**3. Apprentissage par renforcement** : L\'agent apprend par essai-erreur\n\nVoulez-vous approfondir l\'un de ces concepts ?',
  python: 'Python est le langage de prédilection pour la Data Science et l\'IA grâce à ses bibliothèques puissantes : **NumPy**, **Pandas**, **Scikit-learn**, **TensorFlow**, et **PyTorch**. Sa syntaxe claire le rend idéal pour les algorithmes complexes.',
  docker: 'Docker vous permet de containeriser vos applications pour un déploiement cohérent sur n\'importe quel environnement. Les concepts clés sont :\n\n• **Image** : Template immuable de votre application\n• **Container** : Instance en cours d\'exécution\n• **Dockerfile** : Instructions pour construire l\'image\n• **Docker Compose** : Orchestration multi-conteneurs',
};

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'student-1',
    title: 'Nouveau cours disponible',
    message: 'Le cours "NLP avec Transformers" vient d\'être publié par Dr. Amira Ben Salah',
    type: 'info',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    link: '/student/courses',
  },
  {
    id: 'notif-2',
    userId: 'student-1',
    title: 'Quiz réussi !',
    message: 'Félicitations ! Vous avez obtenu 85% au quiz "Algorithmes de classification"',
    type: 'success',
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'student-1',
    title: 'Rappel de progression',
    message: 'Continuez votre élan ! Vous avez 72% de progression sur le cours d\'IA',
    type: 'warning',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const chartData = {
  monthlyEnrollments: [
    { month: 'Jan', étudiants: 120, cours: 8 },
    { month: 'Fév', étudiants: 185, cours: 12 },
    { month: 'Mar', étudiants: 240, cours: 15 },
    { month: 'Avr', étudiants: 310, cours: 18 },
    { month: 'Mai', étudiants: 280, cours: 22 },
    { month: 'Jun', étudiants: 420, cours: 25 },
    { month: 'Jul', étudiants: 380, cours: 28 },
    { month: 'Aoû', étudiants: 510, cours: 30 },
    { month: 'Sep', étudiants: 620, cours: 35 },
    { month: 'Oct', étudiants: 740, cours: 40 },
    { month: 'Nov', étudiants: 890, cours: 45 },
    { month: 'Déc', étudiants: 1050, cours: 52 },
  ],
  categoryDistribution: [
    { name: 'Intelligence Artificielle', value: 35, color: '#6366f1' },
    { name: 'Développement Web', value: 28, color: '#8b5cf6' },
    { name: 'Data Science', value: 20, color: '#06b6d4' },
    { name: 'DevOps', value: 10, color: '#f59e0b' },
    { name: 'Autres', value: 7, color: '#10b981' },
  ],
  weeklyActivity: [
    { day: 'Lun', heures: 2.5 },
    { day: 'Mar', heures: 4 },
    { day: 'Mer', heures: 3.5 },
    { day: 'Jeu', heures: 5 },
    { day: 'Ven', heures: 2 },
    { day: 'Sam', heures: 6.5 },
    { day: 'Dim', heures: 3 },
  ],
};
