apiVersion: 1

contactPoints:
  - orgId: 1
    name: email-eduai
    receivers:
      - uid: email-receiver-main
        type: email
        settings:
          addresses: adibrezgui2001@gmail.com
          singleEmail: false
        disableResolveMessage: false
